language: node_js

node_js:
  - "10"
  - "12"
  - "14"

os:
  - linux
  - osx
  - windows

git:
  autocrlf: false

script:
  - npm run validate
  - npm run build
  - npm run examples-build
  - npm run test
