query User {
  user {
    ...userFields
  }
}

query Messages {
  lastMessage {
    ...messageFields
  }
  messages {
    ...messageFields
  }
}

fragment userFields on User {
  id
  name
  email
}

fragment messageFields on Message {
  id
  from {
    ...userFields
  }
  message
}
