# Enums

enum Language {
  EN
  NL
}

# Schema

schema {
  query: Query
  mutation: Mutation
}

# Query

type Query {
  user: User!
  messages: [Message!]!
  lastMessage: Message
  translation(id: ID!, language: Language): String
}

type User {
  id: ID!
  name: String!
  email: String!
}

type Message {
  id: ID!
  from: User!
  message: String!
}

# Mutation

type Mutation {
  postMessage(message: String!): ID
}
