query {
  user {
    ...userFields
  }

  lastMessage {
    ...messageFields
  }

  messages {
    ...messageFields
  }
}

fragment userFields on User {
  id
  name
  email
}

fragment messageFields on Message {
  id
  from {
    ...userFields
  }
  message
}
