# Schema

schema {
  query: Query
}

# Query

type Query {
  i: Person!
  me: Person!
  you: Person
}

type Person {
  name: String!
  age: Int
  email: String
  dog: Dog
  parents: [Person!]!
  siblings: [Person]!
  family: [Person!]
  friends: [Person]
}

type Dog {
  name: String
  color: String!
}
