name: Build and Test
on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # needs git config core.autocrlf input

        node_version:
          - 16
          - 18

    name: Node ${{ matrix.node_version }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Validate code
        run: npm run validate

      - name: Build library
        run: npm run build

      - name: Build examples
        run: npm run examples-build

      - name: Run tests
        run: npm run test
